load("@rules_hdl//verilog:providers.bzl", "verilog_library")

# BUILD overlay for stock openhwgroup/cva6 (upstream ships no Bazel).
# Derived from core/Flist.cva6 for the cv64a6_imafdc_sv39 (WT-cache) config.
# hpdcache sources are omitted — this config instantiates the write-through
# cache subsystem, so the hpdcache generate branch is never elaborated.
package(default_visibility = ["//visibility:public"])

# --- Include-fragment libraries, one per `+incdir` namespace. Each hdr's
# --- directory becomes a Verilator -I path; strip_include_prefix truncates
# --- it so `\`include "ns/foo.svh"` resolves (see rules_hdl_compat).

# Bare includes: `\`include "rvfi_types.svh"`, `\`include "cvxif_types.svh"`.
verilog_library(
    name = "cva6_hdr_core",
    hdrs = glob(["core/include/*.svh"]),
)

# `\`include "common_cells/registers.svh"`. Sourced from bazel_include/ (staged
# by cva6_ext.bzl) so the namespace appears once and the +incdir lands on
# bazel_include/ rather than being truncated early (rules_hdl_compat first-match).
verilog_library(
    name = "cva6_hdr_common_cells",
    hdrs = glob(["bazel_include/common_cells/*.svh"]),
    strip_include_prefix = "common_cells",
)

# `\`include "axi/typedef.svh"`, `\`include "axi/assign.svh"`.
verilog_library(
    name = "cva6_hdr_axi",
    hdrs = glob(["bazel_include/axi/*.svh"]),
    strip_include_prefix = "axi",
)

# Bare includes from the tracer: `\`include "instr_trace_item.svh"`, etc.
verilog_library(
    name = "cva6_hdr_util",
    hdrs = glob(["common/local/util/*.svh"]),
)

# The core RTL. Includes the `ariane` wrapper (corev_apu/src/ariane.sv) and
# the `cva6_rvfi` probe expander so the harness can instantiate both.
verilog_library(
    name = "cv64a6_imafdc_sv39",
    srcs = [
        "vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv",
        "vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv",
        "vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv",
        "vendor/pulp-platform/fpga-support/rtl/SyncThreePortRam.sv",
        "vendor/pulp-platform/fpga-support/rtl/SyncDpRam_ind_r_w.sv",
        "core/cvfpu/src/fpnew_pkg.sv",
        "core/cvfpu/src/fpnew_cast_multi.sv",
        "core/cvfpu/src/fpnew_classifier.sv",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v",
        "core/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v",
        "core/cvfpu/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v",
        "core/cvfpu/src/fpnew_divsqrt_th_32.sv",
        "core/cvfpu/src/fpnew_divsqrt_th_64_multi.sv",
        "core/cvfpu/src/fpnew_divsqrt_multi.sv",
        "core/cvfpu/src/fpnew_fma_multi.sv",
        "core/cvfpu/src/fpnew_fma.sv",
        "core/cvfpu/src/fpnew_noncomp.sv",
        "core/cvfpu/src/fpnew_opgroup_block.sv",
        "core/cvfpu/src/fpnew_opgroup_fmt_slice.sv",
        "core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv",
        "core/cvfpu/src/fpnew_rounding.sv",
        "core/cvfpu/src/fpnew_top.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv",
        "core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv",
        "core/include/config_pkg.sv",
        "core/include/cv64a6_imafdc_sv39_config_pkg.sv",
        "core/include/riscv_pkg.sv",
        "core/include/ariane_pkg.sv",
        "core/include/wt_cache_pkg.sv",
        "core/include/std_cache_pkg.sv",
        "core/include/instr_tracer_pkg.sv",
        "core/include/build_config_pkg.sv",
        "core/include/aes_pkg.sv",
        "core/include/triggers_pkg.sv",
        "core/cvxif_compressed_if_driver.sv",
        "core/cvxif_issue_register_commit_if_driver.sv",
        "core/cvxif_example/include/cvxif_instr_pkg.sv",
        "core/cvxif_fu.sv",
        "core/cvxif_example/cvxif_example_coprocessor.sv",
        "core/cvxif_example/instr_decoder.sv",
        "core/cvxif_example/compressed_instr_decoder.sv",
        "core/cvxif_example/copro_alu.sv",
        "vendor/pulp-platform/common_cells/src/cf_math_pkg.sv",
        "vendor/pulp-platform/common_cells/src/fifo_v3.sv",
        "vendor/pulp-platform/common_cells/src/lfsr.sv",
        "vendor/pulp-platform/common_cells/src/lfsr_8bit.sv",
        "vendor/pulp-platform/common_cells/src/stream_arbiter.sv",
        "vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv",
        "vendor/pulp-platform/common_cells/src/stream_mux.sv",
        "vendor/pulp-platform/common_cells/src/stream_demux.sv",
        "vendor/pulp-platform/common_cells/src/lzc.sv",
        "vendor/pulp-platform/common_cells/src/rr_arb_tree.sv",
        "vendor/pulp-platform/common_cells/src/shift_reg.sv",
        "vendor/pulp-platform/common_cells/src/unread.sv",
        "vendor/pulp-platform/common_cells/src/popcount.sv",
        "vendor/pulp-platform/common_cells/src/exp_backoff.sv",
        "vendor/pulp-platform/common_cells/src/counter.sv",
        "vendor/pulp-platform/common_cells/src/delta_counter.sv",
        "core/cva6.sv",
        "core/cva6_rvfi_probes.sv",
        "core/alu.sv",
        "core/alu_wrapper.sv",
        "core/aes.sv",
        "core/fpu_wrap.sv",
        "core/branch_unit.sv",
        "core/compressed_decoder.sv",
        "core/macro_decoder.sv",
        "core/controller.sv",
        "core/zcmt_decoder.sv",
        "core/csr_buffer.sv",
        "core/csr_regfile.sv",
        "core/trigger_module.sv",
        "core/decoder.sv",
        "core/ex_stage.sv",
        "core/instr_realign.sv",
        "core/id_stage.sv",
        "core/issue_read_operands.sv",
        "core/issue_stage.sv",
        "core/load_unit.sv",
        "core/load_store_unit.sv",
        "core/lsu_bypass.sv",
        "core/mult.sv",
        "core/multiplier.sv",
        "core/serdiv.sv",
        "core/perf_counters.sv",
        "core/ariane_regfile_ff.sv",
        "core/ariane_regfile_fpga.sv",
        "core/scoreboard.sv",
        "core/raw_checker.sv",
        "core/store_buffer.sv",
        "core/amo_buffer.sv",
        "core/store_unit.sv",
        "core/commit_stage.sv",
        "core/axi_shim.sv",
        "core/cva6_accel_first_pass_decoder_stub.sv",
        "core/acc_dispatcher.sv",
        "core/cva6_fifo_v3.sv",
        "core/frontend/btb.sv",
        "core/frontend/bht.sv",
        "core/frontend/bht2lvl.sv",
        "core/frontend/ras.sv",
        "core/frontend/instr_scan.sv",
        "core/frontend/instr_queue.sv",
        "core/frontend/frontend.sv",
        "core/cache_subsystem/wt_dcache_ctrl.sv",
        "core/cache_subsystem/wt_dcache_mem.sv",
        "core/cache_subsystem/wt_dcache_missunit.sv",
        "core/cache_subsystem/wt_dcache_wbuffer.sv",
        "core/cache_subsystem/wt_dcache.sv",
        "core/cache_subsystem/cva6_icache.sv",
        "core/cache_subsystem/wt_cache_subsystem.sv",
        "core/cache_subsystem/wt_axi_adapter.sv",
        "core/cache_subsystem/tag_cmp.sv",
        "core/cache_subsystem/axi_adapter.sv",
        "core/cache_subsystem/miss_handler.sv",
        "core/cache_subsystem/cache_ctrl.sv",
        "core/cache_subsystem/cva6_icache_axi_wrapper.sv",
        "core/cache_subsystem/std_cache_subsystem.sv",
        "core/cache_subsystem/std_nbdcache.sv",
        "core/pmp/src/pmp.sv",
        "core/pmp/src/pmp_entry.sv",
        "core/pmp/src/pmp_data_if.sv",
        "common/local/util/instr_tracer.sv",
        "common/local/util/tc_sram_wrapper.sv",
        "common/local/util/tc_sram_wrapper_cache_techno.sv",
        "vendor/pulp-platform/tech_cells_generic/src/rtl/tc_sram.sv",
        "common/local/util/sram.sv",
        "common/local/util/sram_cache.sv",
        "core/cva6_mmu/cva6_mmu.sv",
        "core/cva6_mmu/cva6_ptw.sv",
        "core/cva6_mmu/cva6_tlb.sv",
        "core/cva6_mmu/cva6_shared_tlb.sv",
        "corev_apu/tb/ariane_axi_pkg.sv",
        "corev_apu/src/ariane.sv",
        "core/cva6_rvfi.sv",
    ],
    deps = [
        ":cva6_hdr_core",
        ":cva6_hdr_common_cells",
        ":cva6_hdr_axi",
        ":cva6_hdr_util",
    ],
)
